#pragma once
#include <stdint.h>
#include "../config.h"

// GENERATED by tools/screenfit/gen_bias.py from
// hardware-tests/screen-fit/screen-fit.json. Do not hand-edit: the build gate
// regenerates this and fails if it differs from the measurement.
//
// WHAT THIS IS. The four panels are 128x64 in memory, but not all of it is
// visible through the case. Each module's lit rectangle sits off the module
// PCB's own centre in Y (case/measurements.json, ACTIVE_OFFSET = 2.1 mm), and
// all four are mounted with their headers facing the board's centreline, so
// that offset is MIRRORED between the rows. Every panel loses rows on the edge
// that faces the middle of the clock.
//
// MEASURED BY EYE, THROUGH THE ASSEMBLED CASE, on 2026-08-11:
//   TL HOUR  ch2  visible y  0..59  middle 29.5  bias -2
//   TR MIN   ch6  visible y  0..59  middle 29.5  bias -2
//   BL DAY   ch1  visible y  4..63  middle 33.5  bias +2
//   BR DATE  ch7  visible y  4..63  middle 33.5  bias +2
//
// Horizontal loss was zero on all four (x 0..127 visible), which independently
// confirms measurements.json's "the offset is in Y ONLY" from a completely
// separate kind of evidence.
//
// Without this bias the firmware centres every layout on y 31.5 -- the middle
// of the buffer, not the middle of what you can see -- so the top row reads
// 2 px low and the bottom row 2 px high, a 4 px disagreement between the rows.
// That is exactly the symptom that was reported by eye: "MON and AUG 10 are
// sitting a touch too high", while the top two looked fine.
//
// Applied in the blit, in CANVAS space, alongside the burn-in shift -- which
// is the viewer's frame, so the mounting rotation cannot negate it. See
// blit_map.h for why naming the frame matters here.
static const int8_t SLOT_BIAS_Y[N_SCREENS] = {-2, -2, +2, +2};

// The largest bias any slot carries. The safe area must give up this much at
// the top AND the bottom on top of the burn-in shift, or ink that sits at the
// edge of the safe area would clip once the bias and the shift point the same
// way. display.h folds it into SAFE_Y0/SAFE_Y1.
static const int16_t BIAS_MAX = 2;
